version: '3'

services:

  template_pkg:
    build:
      context: $ROOT_DIR/
      dockerfile: $ROOT_DIR/Dockerfile
    image: template_pkg:latest
    network_mode: host
    ipc: host
    pid: host
    environment:
      - INPUT_TOPIC=$INPUT_TOPIC
      - WHEEL_DISTNCE=$WHEEL_DISTNCE
      - MAX_WHEEL_SPEED=$MAX_WHEEL_SPEED
    command: ros2 launch template_pkg template_pkg.launch.py

  pub_and_sub_pkg:
    build:
      context: $ROOT_DIR/
      dockerfile: $ROOT_DIR/Dockerfile
    image: template_pkg:latest
    network_mode: host
    ipc: host
    pid: host
    environment:
      - INPUT_TOPIC=$INPUT_TOPIC
      - WHEEL_DISTNCE=$WHEEL_DISTNCE
      - MAX_WHEEL_SPEED=$MAX_WHEEL_SPEED
    command: ros2 launch template_pkg pub_and_sub.launch.py